#! /usr/bin/env bash
#
# Import and patch up external files.
#
# Not the generic script because we provide a semgrep-specific scanner.c
#
set -eu -o pipefail

name=$(basename "$(pwd)" | sed -e 's/semgrep-//')

mkdir -p src
(
  cd src
  scanner_c=../../tree-sitter-"$name"/src/scanner.c

  if ! [ -f "scanner.c" ]; then
    # Scanner does not exist
    echo "Copying and patching tree-sitter scanner..."

    if [[ -e "$scanner_c" ]]; then
      cp "$scanner_c" scanner.c
    fi

    patch scanner.c ../patch.diff
  else
    # Scanner does exist
    # We might have made edits to it, so let's update the
    # patch file.
    echo "Scanner exists, updating patch file..."

    if [[ -e "$scanner_c" ]]; then
      cp "$scanner_c" scanner_orig.c
    fi

    # || true because diff returns a bad exit code if there are differences
    diff -b scanner_orig.c scanner.c > ../patch.diff || true

    rm scanner_orig.c
  fi
)

mkdir -p test/corpus
(
  cd test/corpus
  rm -f inherited
  # The root of the tests is either 'test/corpus' or 'corpus' as per
  # tree-sitter documentation.
  for dir in test/corpus corpus; do
    corpus=../../../tree-sitter-"$name"/$dir
    if [[ -e "$corpus" ]]; then
      ln -sf "$corpus" inherited
    fi
  done
)
