#! /usr/bin/env bash
#
# Import and patch up external files.
#
# This is a Haskell-specific script, due to the `unicode.h` below. 
#
set -eu -o pipefail

name=$(basename "$(pwd)" | sed -e 's/semgrep-//')

mkdir -p src
(
  cd src
  rm -f scanner.c scanner.cc
  scanner_c=../../tree-sitter-"$name"/src/scanner.c
  scanner_cc="$scanner_c"c
  unicode_h=../../tree-sitter-"$name"/src/unicode.h
  if [[ -e "$scanner_c" ]]; then
    ln -sf "$scanner_c" .
  elif [[ -e "$scanner_cc" ]]; then
    ln -sf "$scanner_cc" .
  fi
  # The Haskell tree-sitter scanner has a dependency on a `unicode.h` file, so
  # we have to bring it over here or we won't be able to make the parser.
  ln -sf "$unicode_h" .
)

mkdir -p test/corpus
(
  cd test/corpus
  rm -f inherited
  # The root of the tests is either 'test/corpus' or 'corpus' as per
  # tree-sitter documentation.
  for dir in test/corpus corpus; do
    corpus=../../../tree-sitter-"$name"/$dir
    if [[ -e "$corpus" ]]; then
      ln -sf "$corpus" inherited
    fi
  done
)
