open Common;

let generate_recursive_parser = (cst_type: string): string => {
   cst_type
}

let codegen = (_rules, generated_cst_filename: string): string => {
   let template = spf("/* DO NOT MODIFY MANUALLY:
   Auto-generated by codegen_json_reader*/
   open %s
   open Common;
   module J = Json_type;
   let error = (s, json) => failwith(spf(\"Wrong format: %s, got: %s\",s,Json_io.string_of_json(json)))
   ", generated_cst_filename);

   /*
      TODO: refactor codegen_type to emit extra
      Structure of generated code:
      - recursive parser for complex types
      - parse_body
      - entrypoint
   */
   template ++ generate_recursive_parser(generated_cst_adt)
}
