#! /usr/bin/env bash
#
# Import and patch up external files.
#
# Not the generic script, because we've updated our version of the Julia
# grammar to return a slightly different syntax tree
#
set -eu -o pipefail

RED='\033[0;31m'
NC='\033[0m' # No Color

name=$(basename "$(pwd)" | sed -e 's/semgrep-//')
echo $(pwd)

mkdir -p src
(
  cd src
  rm -f scanner.c scanner.cc
  scanner_c=../../tree-sitter-"$name"/src/scanner.c
  scanner_cc="$scanner_c"c
  unicode_h=../../tree-sitter-"$name"/src/unicode.h
  if [[ -e "$scanner_c" ]]; then
    ln -sf "$scanner_c" .
  elif [[ -e "$scanner_cc" ]]; then
    ln -sf "$scanner_cc" .
  fi
)

mkdir -p test/corpus
(
  cd test/corpus
  rm -f inherited
  # The root of the tests is either 'test/corpus' or 'corpus' as per
  # tree-sitter documentation.
  for dir in test/corpus corpus; do
    corpus=../../../tree-sitter-"$name"/$dir
    if [[ -e "$corpus" ]]; then
      ln -sf "$corpus" inherited
      echo -e "${RED}"
      echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
      echo "Your Julia tests may fail due to us changing the syntax tree slightly."
      echo "If you have a failing test due to 'interpolation_expression' being"
      echo "parsed as 'identifier', ignore it, as it is expected behavior."
      echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
      echo -e "${NC}"
    fi
  done
)
