#! /usr/bin/env bash
#
# Import and patch up external files.
#
# Not the generic script because of tree_sitter_html/
#
set -eu -o pipefail

mkdir -p src

rm -f src/scanner.cc
cat ../tree-sitter-vue/src/scanner.cc \
  | sed -e 's:"./tree_sitter_html/scanner.cc":"scanner_html.h":' \
  > src/scanner.cc

(
  cd src
  ln -sf ../../tree-sitter-vue/src/tree_sitter_html/scanner.cc scanner_html.h
  ln -sf ../../tree-sitter-vue/src/tree_sitter_html/tag.h tag.h
)

mkdir -p test/corpus
(
  cd test/corpus
  rm -f inherited
  ln -sf ../../../tree-sitter-vue/corpus inherited
)
