name: Python tests

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  test-update-grammar:
    name: scripts/test_update_grammar.py
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.9'
      - run: python -m unittest scripts/test_update_grammar.py
